services:

  postgres:
    image: postgres:16-alpine

    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 10

    networks:
      - knowledge-search-network

  redis:
    image: redis:7-alpine

    restart: unless-stopped

    ports:
      - "${REDIS_PORT}:6379"

    volumes:
      - redis_data:/data

    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 10

    networks:
      - knowledge-search-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.1

    restart: unless-stopped

    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"

    ports:
      - "${ELASTICSEARCH_PORT}:9200"

    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

    networks:
      - knowledge-search-network

networks:
  knowledge-search-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  elasticsearch_data:
