version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../docker/postgres/init:/docker-entrypoint-initdb.d

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10

    networks:
      - knowledge-search-network

  redis:
    image: redis:7-alpine
    container_name: redis

    restart: unless-stopped

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 10

    networks:
      - knowledge-search-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.1.1
    container_name: elasticsearch

    restart: unless-stopped

    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"

    ports:
      - "9200:9200"

    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

    healthcheck:
      test: [ "CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:9200 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 20

    networks:
      - knowledge-search-network

  search-engine:
    build:
      context: ../../search-engine
      dockerfile: Dockerfile

    container_name: search-engine

    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

    ports:
      - "8080:8080"
      - "9090:9090"

    networks:
      - knowledge-search-network

  document-processor:
    build:
      context: ../../document-processor
      dockerfile: Dockerfile

    container_name: document-processor

    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy
      search-engine:
        condition: service_started

    ports:
      - "8081:8081"
      - "9091:9091"

    networks:
      - knowledge-search-network

networks:
  knowledge-search-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  elasticsearch_data:
